### ISSUE TITLE
Unsigned integer literals still showing up red in the IDE

### ISSUE THREAD

**Issue by russhwolf** [LouisCAD/CompleteKotlin#2]
I tried adding the plugin to Multiplatform Settings, and looking at code in the mingwX64 target from a macOS machine. Worked great for the most part, but was still seeing red code around unsigned integers. See screenshot for example

![Screen Shot 2021-06-03 at 5 37 26 PM](https://user-images.githubusercontent.com/3256243/120718425-3bf5c380-c497-11eb-986b-547379df9428.png)

**Comment by LouisCAD** [comment]
@russhwolf Do you have the same issue if reading the code in IDE in Windows?

@sellmair Do you know what could be the cause of this issue?

**Comment by sellmair** [comment]
I do have a slight idea what might be going on. Maybe the native stdlib is not attached to the mingw source set. 
My investigation can be tracked here: 
https://youtrack.jetbrains.com/issue/KT-47124

👍

**Comment by sellmair** [comment]
Can you please try if 

```kotlin
    sourceSets.configureEach {
        languageSettings.apiVersion = "1.5"
        languageSettings.languageVersion = "1.5"
    }
```

Resolves your issue?

**Comment by sellmair** [comment]
This is not a CompleteKotlin issue: 
Root cause can be tracked here: https://youtrack.jetbrains.com/issue/KTIJ-18938
Workaround above should work ✅
