### ISSUE TITLE
How to troubleshoot?

### ISSUE THREAD

**Issue by rocketraman** [LouisCAD/CompleteKotlin#4]
Didn't seem to work for me. How can I troubleshoot? I did see the Gradle build output included a download and unpack of some files into `$HOME/.konan`.

Some imports that are still red:

![image](https://user-images.githubusercontent.com/53049/121639991-5dd4e480-ca5b-11eb-9e88-39da292de436.png)

![image](https://user-images.githubusercontent.com/53049/121640035-688f7980-ca5b-11eb-8987-443064c9a6d8.png)

I'm on Linux (Fedora 32) with IntelliJ Ultimate 2021.1.2.

**Comment by LouisCAD** [comment]
Hello!

Which Kotlin version is the project using?
Can you try with a freshly created project from the IDE wizard to see if you get the same issue? If not, can you then try to edit the Kotlin version so that it matches the project you have an issue with?

**Comment by rocketraman** [comment]
Kotlin 1.4.32. I'll try a freshly created project.

**Comment by LouisCAD** [comment]
Hello @rocketraman! Did it work on a new project?

**Comment by rocketraman** [comment]
Nope, didn't work on a new project either.

**Comment by LouisCAD** [comment]
What type of project did you create?

**Comment by rocketraman** [comment]
Kotlin multiplatform mobile on JDK 1.8 with IntelliJ IDEA 2021.1.3.

![image](https://user-images.githubusercontent.com/53049/123972345-c2af9a80-d988-11eb-9408-cef103941ce7.png)

**Comment by rocketraman** [comment]
@LouisCAD  Any ideas?

**Comment by LouisCAD** [comment]
@rocketraman I don't have any, but we can try to dig deeper in a pairing session if you want, sometime this week.

**Comment by LouisCAD** [comment]
Is it the same issue as #6?

**Comment by rocketraman** [comment]
No, I have both `kotlin.mpp.enableGranularSourceSetsMetadata=true` and `kotlin.native.enableDependencyPropagation=false` set.

I thought the problem might be `kotlin.native.ignoreDisabledTargets=true` but commenting that out didn't help either.

**Comment by rocketraman** [comment]
Upstream issue reference: https://youtrack.jetbrains.com/issue/KT-48337

**Comment by LouisCAD** [comment]
So, to answer your question "How to troubleshoot?", I think we're figuring it out 😄

**Comment by rocketraman** [comment]
@LouisCAD I commented in the upstream issue as well but FYI I can no longer reproduce this with modern versions of the IDE and Kotlin. Its working well now! I'll close. Thanks!

**Comment by LouisCAD** [comment]
Yup, I've seen. Thanks for the update, I'm glad the IntelliJ Platform fixed that!
